package g1s1Package;

public enum Commands {
	
	START, FOREST, ZEN_GARDEN, MANSION, STUDY, GREAT_HALL, ROOM, PRESIDENTS_HALL, DOWNSTAIRS, ART_MUSEUM, 
	STORAGE, DUNGEON, EAST, WEST, NORTH, SOUTH, STAIRS, BACK, UPSTAIRS, NAMASTE 

}
